(BE #1) Add relaxed dependency and converter router
transkript/html2pdf-web pull request #2
Opened 2023-09-27 23:06 UTC by elroykanye

2023-09-27 23:27 UTC, Burnleydev1 requested changes
I have left some few comments, but I think everything else is fine.

2023-09-28 08:44 UTC, Burnleydev1 commented on public/javascripts/html2pdf.js
> +module.exports = new HTML2PDF();
please ensure that there is an empty line at the end

2023-09-28 08:49 UTC, Dezzy12 approved these changes
LG!

2023-09-28 08:55 UTC, Burnleydev1 approved these changes
LGTM

2023-09-28 09:26 UTC, merged